orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add', views.add_to_cart, name='add_to_cart'),
    path('cart/delete', views.delete_cart, name='delete_cart')
]

pizza/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("orders.urls")),
    path("admin/", admin.site.urls),
]

orders/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    """Food categories"""
    class Meta:
        verbose_name_plural = "categories"

    category_name = models.CharField(max_length=100)
    order_nr = models.IntegerField(default=0)

    def __str__(self):
        return self.category_name


class Item(models.Model):
    """Food items"""
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=100)
    max_toppings = models.IntegerField(null=True)

    def __str__(self):
        return self.item_name


class Pricing(models.Model):
    """Prices by item with multiple sizes"""
    PRICING_TYPES = (
        ('S', 'Small'),
        ('L', 'Large'),
        ('N', 'N/A'),
    )
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    pricing_type = models.CharField(max_length=1, choices=PRICING_TYPES)
    price = models.DecimalField(max_digits=12, decimal_places=2)

    def __str__(self):
        if self.pricing_type != 'N':
            return f"{self.item.category} {self.item} {self.get_pricing_type_display()}: ${self.price}"
        return f"${self.price}"


class Topping(models.Model):
    """Toppings for pizzas"""
    topping_name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.topping_name}"


class Cart(models.Model):
    """Cart containing pricing items"""
    is_completed = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Cart nr {self.pk}"


class CartItem(models.Model):
    """Item added to the shopping cart"""
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    pricing_item = models.ForeignKey(Pricing, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.cart}, item: {self.pricing_item}"

orders/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from django.views import generic

from .models import Category, Pricing, Cart, CartItem

# Create your views here.


class IndexView(generic.ListView):
    template_name = 'orders/index.html'
    context_object_name = 'categories'

    def get_queryset(self):
        """Return the categories sorted by order_nr"""
        return Category.objects.order_by('order_nr')


class CartView(generic.DetailView):
    model = Cart
    
    def get_object(self):
        if not self.request.session.has_key('cart_id'):
            return None
        cart_id = self.request.session['cart_id']
        return Cart.objects.get(pk=cart_id)


@require_http_methods(["POST"])
def add_to_cart(request):
    pricing_id = int(request.POST['pricing_id'])
    pricing_item = Pricing.objects.get(pk=pricing_id)
    if request.session.has_key('cart_id'):
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(pk=cart_id)
        cart.cartitem_set.add(CartItem(pricing_item=pricing_item), bulk=False)
        cart.save()
    else:
        cart = Cart()
        cart.save()
        cart.cartitem_set.add(CartItem(pricing_item=pricing_item), bulk=False) # pylint: disable=E1101
        cart.save()
        request.session['cart_id'] = cart.pk
    return HttpResponseRedirect(reverse('orders:cart'))


@require_http_methods(["POST"])
def delete_cart(request):
    cart_id = request.session['cart_id']
    cart = Cart.objects.get(pk=cart_id)
    cart.is_deleted = True
    cart.save()
    del request.session['cart_id']
    return HttpResponseRedirect(reverse('orders:cart'))

orders/templates/orders/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap-4.1.3-dist/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap-4.1.3-dist/js/bootstrap.min.js' %}"></script>
    <title>Pinnochio's Pizzas</title>
</head>
<body>
    {% include 'orders/navbar.html' %}
    <p>{{ request.urlconf }}</p>
    <div class="container">
        <h1>{% block title %}{% endblock %}</h1>
        <div>
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

orders/templates/orders/cart_detail.html
{% extends 'orders/base.html' %}
{% load tz %}
{% block title %}Cart{% endblock %}
{% block content %}
    {% if cart %}
    <h2>{{ cart }}</h2>
    <p class="text-muted">Created at {{ cart.created_at|timezone:"Europe/Paris" }}, updated at {{ cart.updated_at|timezone:"Europe/Paris" }}</p>
    <ul>
        {% for cartitem in cart.cartitem_set.all %}
        <li>{{ cartitem.pricing_item }}</li>
        {% endfor %}
    </ul>
    <div>
        <form action="{% url 'orders:delete_cart' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Delete cart" class="btn btn-danger">
        </form>
    </div>
    {% else %}
    <p>Please add at least an item to your cart</p>
    {% endif %}
{% endblock %}

orders/templates/orders/index.html
{% extends 'orders/base.html' %}
{% block title %}Pizzas{% endblock %}
{% block content %}
    {% for category in categories %}
    <div>
        <h2>{{ category }}</h2>
        <ul class="list-group list-group-flush">
            {% for item in category.item_set.all %}
            <li class="list-group-item d-flex justify-content-between">
                {{ item }}
                <div>
                {% for pricing in item.pricing_set.all %}
                    <div class="m-2 text-muted">
                        <form method="post" action="{% url 'orders:add_to_cart' %}" class="form-inline">
                            {% csrf_token %}
                            <input type="hidden" name="pricing_id" value="{{ pricing.pk }}">
                            {% if pricing.pricing_type != 'N' %}
                                {{ pricing.get_pricing_type_display }}: 
                            {% endif %}
                            ${{ pricing.price }}
                            <input type="submit" value="Add to cart" class="btn btn-default btn-sm ml-2 pull-right">
                        </form>
                    </div>
                {% endfor %}
                </div>
            </li>
            {% empty %}
            <li>No subcategory</li>
            {% endfor %}
        </ul>
    </div>
    {% endfor %}
{% endblock %}

orders/templates/orders/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-basilic">
    <a class="navbar-brand" href="{% url 'orders:index' %}">Pinnochio's Pizzas</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            {% with url_name=request.resolver_match.url_name %}
            <li class="nav-item{% if url_name == 'index' %} active{% endif %}">
                <a class="nav-link" href="{% url 'orders:index' %}">Home</a>
            </li>
            <li class="nav-item{% if url_name == 'cart' %} active{% endif %}">
                <a class="nav-link" href="{% url 'orders:cart' %}">Cart</a>
            </li>
            {% endwith %}
        </ul>
    </div>
</nav>